package com.hyperscalelogic.soundstrip.cfg

object AppCfg {
  val TEXT_ENRICHER_CACHE_SIZE_BYTES = 128 * 1024 * 1024

  val APP_CTX_BITMAP_CACHE_SIZE_BYTES = 64 * 1024 * 1024

  val APP_CTX_BITMAP_DRAWALBE_CACHE_MAX_COUNT =  64

  val TRACK_STORE_TRACK_BATCH_COUNT = 32

  val ALBUM_STORE_ALBUM_BATCH_COUNT = 32

  val CACHED_TRACK_STORE_MAX_IDS_COUNT = 512

  val CACHED_TRACK_STORE_IDS_EVICT_SECS = 15

  val CACHED_TRACK_STORE_MAX_TRACKS_COUNT = 512

  val CACHED_TRACK_STORE_TRACKS_EVICT_SECS = 15

  val CACHED_ALBUM_STORE_MAX_IDS_COUNT = 512

  val CACHED_ALBUM_STORE_IDS_EVICT_SECS = 5

  val CACHED_ALBUM_STORE_MAX_ALBUMS_COUNT = 512

  val CACHED_ALBUM_STORE_ALBUMS_EVICT_SECS = 5

}
